import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.GateLemmas
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.FinalTheorem
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.JordanCanonicalForm
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.RationalCanonicalForm
import HautevilleHouse.CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean.SmithNormalForm

namespace HautevilleHouse
namespace CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean

-- Marker theorem: all canonical forms reduce to admissible closure
theorem canonical_forms_classification_foundation_endgame :
    ∀ A : AdmissibleClass, ConstrainedCanonicalFormsClosure A := by
  intro A
  exact canonical_forms_endgame A

end CanonicalFormsReductionsClassificationFoundationCanonicalLaneLean
end HautevilleHouse
